# -*- coding: utf-8 -*-
"""TicTacToe

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G6qsHD-0UtFqGsABIyObaQvf_y-m1KNS
"""

board =    {'1': ' ', '2': ' ', '3': ' ',
            '4': ' ', '5': ' ', '6': ' ',
            '7': ' ', '8': ' ', '9': ' '}

def printboard(board):
 print(board['1'] + '|' + board['2'] + '|' + board['3'])
 print('-+-+-')
 print(board['4'] + '|' + board['5'] + '|' + board['6'])
 print('-+-+-')
 print(board['7'] + '|' + board['8'] + '|' + board['9'])


print("the positions you can choose are the following")
for i in board.keys():
  print(i , end = " ")
print("\n")


tie = True
turn = 'X'
for i in range(9):
  printboard(board)
  print('Turn for ' + turn + '. Move on which space?')

  move = input()
  while move not in board.keys() or board[move] != ' ':
    print("that is not a valid input, you can only choose positions from 1 to 9 and only positions that are not already occupied")
    print("let´s try it again. Move on which space?")
    move = input()

  
  board[move] = turn

  if (board['1'] == board['2'] and board['1'] == board['3'] or board['1'] == board['4'] and board['1'] == board['7'] or board['1'] == board['5'] and board['1'] == board['9']) and board['1'] != " ":
    print(f"{board['1']} won the game.")
    tie = False
    break
  elif (board['4'] == board['5'] and board['4'] == board['6']) and board['4'] != " ":
    print(f"{board['4']} won the game.")
    tie = False
    break
  elif (board['7'] == board['8'] and board['7'] == board['9'] or board['7'] == board['5'] and board['7'] == board['3']) and board['7'] != " ":
    print(f"{board['7']} won the game.")
    tie = False
    break
  elif (board['2'] == board['5'] and board['2'] == board['8']) and board['2'] != " ":
    print(f"{board['2']} won the game.")
    tie = False
    break
  elif (board['3'] == board['6'] and board['3'] == board['9']) and board['3'] != " ":
    print(f"{board['3']} won the game.")
    tie = False
    break

  if turn == 'X':
    turn = 'O'
  else:
    turn = 'X'
if tie:
  print("It´s a tie!")
  
printboard(board)